modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/RFToolsBase/issues"
displayURL="http://github.com/McJtyMods/RFToolsBase/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="rftoolsbase"
version="${file.jarVersion}"
displayName="RFToolsBase"
#updateJSONURL="http://myurl.me/" #optional
description='''
The base class for all RFTools tech mods (and XNet/Deep Resonance)
'''
[[dependencies.rftoolsbase]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolsbase]]
    modId="mcjtylib"
    mandatory=false
    versionRange="[1.15-4.1.7,)"
    ordering="AFTER"
    side="BOTH"